# Generated by Django 3.1.6 on 2021-02-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='highScore',
        ),
    ]
