# Generated by Django 3.1.7 on 2021-02-26 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
