# Generated by Django 3.1.7 on 2021-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0006_auto_20210301_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('emailID', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='ColoPoints',
        ),
    ]
