# Generated by Django 3.1.6 on 2021-03-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0008_remove_userprofile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highScore',
            field=models.CharField(default=500, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='highScore',
            field=models.CharField(max_length=1000),
        ),
    ]
