# Generated by Django 3.1.6 on 2021-03-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0010_auto_20210323_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='emailID',
            field=models.CharField(default='unk', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
