# Generated by Django 3.1.6 on 2021-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0011_usermodel_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='coloPoints',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
