# Generated by Django 3.1.6 on 2021-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0012_usermodel_colopoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='highScoreTrex',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='highScore',
            field=models.CharField(max_length=100),
        ),
    ]
