# Generated by Django 3.1.7 on 2021-03-26 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colos', '0013_auto_20210325_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marketing_maestro_coins',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='MarketingMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, upload_to='brand_images')),
                ('product_title', models.CharField(max_length=250)),
                ('total_value', models.IntegerField()),
                ('branding_video', models.CharField(max_length=300)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
