# Generated by Django 3.1.7 on 2021-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colos', '0015_marketingmaestro_product_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='colo_coins',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
